### ISSUE TITLE
[MM] Replace ObservableCollection in interfaces with something better

### ISSUE THREAD

**Issue by stephenatwork** [microsoft/MixedReality-Sharing#39]
We want to update the discovered rooms from a network task. But ObservableCollection isn't threadsafe. Locking seems inadequate since we don't want to block writers because of slow readers.  Some kind of lightweight snapshot + notification seems like it could work better.

**Comment by fibann** [comment]
We eventually went for 4 above, but soon found that it leads you to write blocks like
```csharp
Func<IDiscoverySubscription> handleUpdate = sub => { ... };
subscription.OnUpdate += handleUpdate;
handleUpdate(subscription);
```
because OnUpdate might never be called. This is a potential big pitfall. So we'll probably switch to option 5.

Note that option 5 might be used with NotifyCollectionChanged, but the fine-grained updates make the implementation more complicated. I'll try and see what the code looks like.

**Comment by stephenatwork** [comment]
For completeness, also discussed was option 5a where the update isn't fired synchronously on the current thread, but 'soon' from the update thread.
